// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdggjvdndxvmykcrtdcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkZ2dqdmRuZHh2bXlrY3J0ZGN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1MzQ1MDgsImV4cCI6MjA1MDExMDUwOH0.urv6fxKvtMr55ZsOtN1kgXBICM59mLiZkxGaM_RmgkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);